### ISSUE TITLE
Too long server descriptions break the bot function

### ISSUE THREAD

**Issue by Northwave** [adamZdrojewski/pterodactylDiscordBot#3]
As described, too long server descriptions in ptero panel are too much for the bot. As i had some more notes for specific servers, i encountered this issue. is there a max char count the bot works with ?

heres my example which triggers the: the interaction failed message in discord:

search in unofficial servers browser: MynameARK Ascended Server, make sure to check the show password protected server box
Game Password: password

**Comment by adamZdrojewski** [comment]
I will take a look!

**Comment by adamZdrojewski** [comment]
Should be all set for you.  Just make sure to pull the new image from Docker Hub!
